steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - cf_cloud_build
  - --region=us-central1
  - --allow-unauthenticated
  - --source=https://source.developers.google.com/projects/cloud-functions01/repos/github_gabrielosluz_cloud_functions_explore/moveable-aliases/main/paths/cloud_build_demo
  - --trigger-http
  - --runtime=python39
  - --memory=128MB
  - --project=cloud-functions01
  - --entry-point=hello_world
  - --update-labels=course=cloud_functions,env=dev,layer=raw