steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - cf_csv_to_parquet
  - --region=us-central1
  - --allow-unauthenticated
  - --source=https://source.developers.google.com/projects/cloud-functions01/repos/github_gabrielosluz_ac_cloud_functions/moveable-aliases/main/paths/cf_csv_to_parquet
  - --trigger-bucket=ac-cf-data-pipeline-raw
  - --runtime=python39
  - --memory=2048MB
  - --project=cloud-functions01
  - --entry-point=main
  - --set-env-vars=GCP_PROJECT=cloud-functions01,BUCKET_RAW=ac-cf-data-pipeline-raw,BUCKET_HIST=ac-cf-data-pipeline-hist
  - --update-labels=course=cloud_functions,env=dev,layer=raw